channel.py, jack_mixer.c, jack_mixer.h, jack_mixer.py, jack_mixer_c.c
* Changes controls for MIDI controllers in channel new / edit dialog to `Gtk.SpinButton`s with range (-1, 127).
* Adds tooltip to controls.
* Changes `Channel` object in C extension to add methods for auto-assigning the CC # for each control (volume, balance, mute, solo) individually.
* When editing channel, channel is only renamed when name actually changes.
Using `SpinButton`s also simplifies handling of the widget values, because they are always numeric and in range, they just have to be converted from `float` to `int`.
One minor disadvantage of `SpinButton`s is that if you enter a value manually via the text entry, it only updates when the focus leaves the widget, e.g. when you  tab to the next one. So if you enter a value in, say, the "Volume" spin button text entry and then …
=> Allow manual setting of MIDI control change numbers

jack_mixer.py
* Rename "Open" menu item to "Open...".
* Rename "SaveAs" menu item to "Save As...".
* Change some menu item mnemonics:
* "New Output _Channel" (different from "_Open...")
* "_Edit Input Channel"
* "E_dit Output Channel"
* "_Remove Input Channel"
* "Re_move Ouput Channel"
* "_Clear" (added)
* Disable "Edit/Remove Input Channel" sub-menu entries initially and when no input channels are left.
* Same for output channels.
=> Add accelerator shortcuts to menu items

channel.py, gui.py, jack_mixer.py, meter.py, scale.py, serialization.py, slider.py
I inserted `log.debug` or `log.warning` calls everywhere where `print()` was used (except test functions in `scale.py` and `test.py`) even if `print` was commented out. I used `log.exception` in one instance, when the creation of the main application instance fails, to give an exception traceback in the logging output, because the GUI dialog only shows the general error message, which isn't that helpful.
Debug logging can be turned on with the `-d/--debug` command line switch.
Logging from the C code is currently independent of this and so not affected by the log level or format settings. I'm looking into integrating this in a subsequent PR.
When I touched a `.py` file I also sorted the imports and did some white-space changes according to PEP-8 (mainly two empty lines between top-level …
=> Use standard-logging module instead of scattered print calls

jack_mixer.py
Also:
* Improves error logging by logging exception traceback when error dialog is used.
* fixes remaining Gtk deprecation warnings.
=> Add 'error_dialog' function to reduce DRY

jack_mixer.c, log.c
To change the log level for the C code, add e.g. `-DLOG_LEVEL=0` to `CFLAGS` when compiling, for example via the environment. The log levels are defined in `log.h`.
=> Minor C logging tweaks

jack_mixer.c
Warning only showed up with `-Wunused-variable` and when configured with `--disable-jackmidi`.
=> Fix 'unused variable' compiler warning

gui.py
Makes setting consistently an int when stored internally, as it already is when read from XML.
=> Coerce midi_behaviour_mode preference setting to int

scale.py
Makes the test code in `scale.py` actually runnable by just running the module as a script.
Should probably be moved into a separate test module later.
=> Fix test code in scale.py

jack_mixer.py
Also, changes "Quit" menu entry to "Hide" when under NSM. Sets keyboard shortcut for Hide to `Ctrl-w` and changes "Narrow/Widen Input Channels" shortcuts to `Ctrl-minus` / `Ctrl-plus` to avoid a conflict.
Relates to: #40
=> When under NSM, menu quit or window close only hides UI

channel.py, jack_mixer.py
* Remember last used settings for new input/outut channel dialogs
(MIDI CCs are always initialized with -1 by default, so they can be
auto-assigned).
* Add mnemonics for all input/output channel dialog fields.
Fixes: #38
=> Channel dialogs usability improvements

channel.py
* Don't create unnecesary nested `Gtk.VBox`.
* Use `Gtk.Box` instead of deprecated `Gtk.VBox`.
* Use `Gtk.Grid` instead of deprecated `Gtk.Table`.
* Left-align field labels.
* Set padding for `Gtk.Frame`s.
* Pack Mode and Value radio buttons into grid instead of into their own
Hboxes, so that they are properly aligned.
Closes: #36
=> Improve channel properties dialog layout

abspeak.py, channel.py, jack_mixer.py, meter.py, slider.py
* Overhaul channel fader/meter layout:
* Put value readout/edit entry and peak value readout next to each other
above the fader and meter. When channels are shrunk, they are displayed
one under the other.
* Add tick marks for left/center/right on balance slider
and add tooltip displaying left/right value. This also
changes the appearance of slider handle depending on theme.
* Convert occurences of `Gtk.HBox` and `Gtk.VBox` to `Gtk.Box`.
* Remove `Gtk.Frame`s from layout and set border style via CSS where needed.
* You can now shrink the width of input *and* output channels and it also
reduces the width of the meter display.
* On project load, give input focus to fader of last added channel and deselect
volume entry widget.
* Some code reorganization and cleanup in `abspeak`, `channel`, …
=> Channel strip UI layout and code improvements

channel.py, jack_mixer.c, jack_mixer.h, jack_mixer.py, jack_mixer_c.c
Refactor / clean-up `channel` module:
* Clean-up class hierarchy
* Use `super()` were appropriate
* Reduce DRY by moving shared code into super class
* Re-use channel property dialog instances
* Update old property syntax
* Change class attributes into instance attributes where appropriate
* Upper-case constant global constant name    
* Module level code re-ordering
* Re-order `Channel` class methods into sections
* Some code reformating / refactoring to keep line length under 100 chars
Refactor / clean-up `jack_mixer` module:
* Move helper methods to inlined functions
* Change class attributes into instance attributes where appropriate
* Re-order `JackMixer` class methods into sections
* Some code reformatting to keep line-length under 100 chars
* Updated copyright notice in file header …
=> jack_mixer and channel modules and MIDI CC assignment refactoring and cleanup

channel.py
Sets color chooser widget to random color when the new output channel dialog
is opened, so the user can preview/change the color.
=> Re-enable / fix setting random color for output channels

Makefile.am, configure.ac
Took care of autotools side of jack_mixer, to be able to build only the jack_mix_box if somebody requires just a headless C mixer application.
To configure the headless build one has to pass the "--disable-gui" cli argument during configuration, in which case python is no longer a requirement.
This takes care of feature request ticket #51
=> Add --disable-gui configure option to allow buidling only jack_mix_box

Makefile.am, abspeak.py, channel.py, gui.py, jack_mixer.py, serialization_xml.py, styling.py
* Move all CSS styles and styling related functions into a new `styling` module.
* Provide helper function to add CSS provider in this module.
* Load default CSS in `JackMixer.create_ui()` using the above function (user CSS files will probably be added in another PR).
* Use CSS classes instead of widget names for channel strip elements (buttons etc.).
* Set background color of toggle buttons in channel strips when hovered or active to more distinct colors.
Fixes: #85
=> Re-organize CSS styling and set distinctive colors for active toggle buttons

jack_mixer.c, jack_mixer.h
* Correctly use assigned CC numbers for volume changes.
* Add MIDI CC output for balance, mute and solo.
=> Fix MIDI CC output for changes originating from UI

abspeak.py, channel.py, gui.py, jack_mixer.py, meter.py, preferences.py, pyproject.toml, scale.py, serialization.py, serialization_xml.py, slider.py, styling.py, test.py
Rationale: make it easier to spot actual errors in output of flake8.
Also adds configuration for `black` to new `pyproject.toml` file.
`nsmclient.py` is left untouched.
Signed-off-by: Christopher Arndt <chris@chrisarndt.de>
=> Re-format all Python code with black

jack_mixer.c
* Added comments for better orientation in backend signal processing code.
* Fixed signal routing of soloed channels: do not mix them into system channels,
i.e. direct and monitoring outs (unless, of course, they are soloed for that
specific output, which is true for the direct out of *that particular* channel
or the monitor out, if monitoring is enabled on *that particular* channel).
Fixes: #96
=> Fix channel solo routing signal to direct out of other channels

meson.build, src/meson.build, src/meson_dist_cython.py
* Add dist script, which compiles Cython source files to be included in the source distribution.
* Make Cython build dependency optional for when source tree already contains the C sources compiled from the Cython source files.
* Print build configuration options when setting up build.
=> Add support for meson dist command

jack_mixer/app.py, jack_mixer/channel.py
Regression introduced by 3a0ecbd.
Apart from the fix, do some refactoring, by renaming params and attributes to
make their intention more obvious and add a source comment explaining how
channel volume initialization works.
Fixes: #113
=> Fix restoring channel volumes on project loading

.flake8, .gitignore, INSTALL.md, data/locale/jack_mixer-de.po, data/locale/jack_mixer.pot, data/locale/meson.build, data/meson.build, jack_mixer/abspeak.py, jack_mixer/app.py, jack_mixer/channel.py, jack_mixer/gui.py, jack_mixer/preferences.py, jack_mixer/scale.py, jack_mixer/serialization_xml.py, jack_mixer/slider.py, tools/compile-messages.py, tools/extract-messages.sh, tools/jack_mixer.sh, tools/merge-messages.py
* Add gettext support and mark translatable strings
* Add i18n message catalog *.pot template for translatable strings
in jack_mixer's Python sources and the stdlib argparse module.
* Add German messages translation for the above.
* Add helper scripts for managing i18n files
* Add support for compiling & installing translation files to
meson build setup.
* Add gettext to list of build dependencies in `INSTALL.md`.
=> Add i18n support

src/jack_mixer.c, src/jack_mixer.h
Before this commit, if you changed jack buffer size, the smaller the buffer, the faster the kmeter peak indicator would fall. This commit makes it fall at the same rate regardless of buffer size.
=> Make kmeter peak indicator fall at same rate regardless of buffer size

jack_mixer/app.py, jack_mixer/nsmclient.py, src/jack_mixer.c, src/log.c
Prefix all log messages in C and Python with [jack_mixer] and unify/add newlines after log messages
No copyright required for this change. Only trivial code changes.
=> Prefix all log messages in C and Python with [jack_mixer] and unify/add newlines after log messages

CHANGELOG.md, INSTALL.md, data/locale/jack_mixer-de.po, data/locale/jack_mixer-es.po, data/locale/jack_mixer-fr.po, data/locale/jack_mixer.pot, jack_mixer/gui.py, meson.build, pyproject.toml
=> feat. replace 'appdirs' (unmaintained) with 'platformdirs'

data/jack_mixer.desktop
This adds NSM related keys to the `*.desktop` file, so NSM tools can find applications which have NSM support.
`X-NSM-Capable`, is used to detect if the application has NSM support. It should ideally become false if the application is build without NSM support.
`X-NSM-Exec`, is the exec name of the application when used in NSM. It can't contain a path (not /usr/bin/ for example) or command line arguments like %f.
If `X-NSM-Exec` value is the same as the Exec value, then `X-NSM-Exec` is not strictly needed, but as the Exec value may change in the future (adding %f or something), I think it's not a bad thing to add it anyway.
As discussed in the nsmd forks issue tracker, https://github.com/jackaudio/new-session-manager/issues/40
=> jack_mixer.desktop, add nsm keys

meson.build, meson_options.txt
The meson build script assumes that it can write to `/etc` for the raysession configuration file, which is not possible on all systems.
All other destination directories respect the prefix, so this is the only one that causes a problem.
This PR makes it configureable, while retaining the original destination by default.
=> Make raysessiondir configureable
