jack_mixer.py
* Let argparse handle positional arg for JACK client name handling.
* Fix positional arg handling so that the JACK client name can actually be set from command line.
* Let argparse handle the `-h/--help` option and usage message.
* Sort stdlib imports first.
=> Use argparse instead of optparse and simplify/fix positional args parsing

channel.py
* Add padding to control group labels
* Add padding to mute/solo button labels
* Make control group label font smaller
=> Improve styling of control groups

jack_mixer.py
OK, this makes almost no sense to me, but this seems to work when loading from -c and menu open.
=> Paned position restore hack

channel.py
* Set max width for channel labels to 12 (wide) resp. 8 (narrow)
* "Ellipside" label if it is too wide.
* Add tooltip with full channel name to label if it is too wide
* Make font size of channel label smaller if set to narrow
* Move channel label and wide/narrow related code into
`Channel` base class, so it works th same for input and output
channels.
* Use `super()` in `Channel` sub-classes where appropriate
* Dont use class attributes in `Channel` class for per-instance
data.
=> Improve channel shrinking/expansion

gui.py, jack_mixer.py, preferences.py
=> Optionally ask for confirmation before quitting 

AUTHORS
So this information doesn't get lost, should the website ever change/move.
=> Add icon creator to AUTHORS file

jack_mixer.py
Fixes: #69 #70
Also improve error message when project file loading fails
=> Don't create empty project file on new NSM session

channel.py, gui.py, jack_mixer.py, preferences.py, scale.py, serialization.py, setup.cfg, slider.py, styling.py
Also adds configuration for `flake8` to new `setup.cfg` file.
=> Fix (or selectively ignore) all flake8 errors and warnings

jack_mix_box.c
- fixed enabling of pickup mode in jack_mix_box
=> Jack mix box fixes

.gitignore, INSTALL.md, docs/jack_mixer.1.rst.in, docs/meson.build, docs/meson_dist_rst2man.py, meson.build
=> Add man page for jack_mixer as ReST format source

docs/CONTRIBUTING.md
=> Add new contributing guide

jack_mixer/gui.py
=> Always trigger writing preferences whan any setting is changed

docs/jack_mix_box.1.rst.in, docs/meson.build
=> Add man page for jack_mix_box

data/locale/jack_mixer-de.po, data/locale/jack_mixer-fr.po, data/locale/jack_mixer.pot, docs/jack_mixer.1.rst.in, jack_mixer/app.py, jack_mixer/gui.py, jack_mixer/preferences.py
Also add combo box to preferences dialog to set language
Fixes: #121
=> Add setting for language

data/jack_mixer.desktop, data/locale/jack_mixer-es.po, data/locale/meson.build, jack_mixer/gui.py
Compiled and tested to be working.
=> Add Spanish translation

jack_mixer/abspeak.py, jack_mixer/channel.py, jack_mixer/gui.py, jack_mixer/preferences.py
=> Abspeak meters optionally reset after a chosen time

jack_mixer/slider.py
In particular, don't jump the fader position to the mouse click, but require a mouse click and a drag to move the fader
=> Make the custom sliders have same mouse behavior as normal gtk sliders

jack_mixer/channel.py, jack_mixer/meter.py, jack_mixer/slider.py
I.e., they don't shrink indefinitely
=> Custom sliders have min width

jack_mixer/app.py, jack_mixer/gui.py, jack_mixer/preferences.py
=> Add meter refresh period as user preference

jack_mixer/nsmclient.py
=> Update nsmclient.py from upstream new-session-manager/extras

README.md, src/_jack_mixer.pxd, src/_jack_mixer.pyx, src/meson.build
Declare MIDI change callback as 'noexcept' as it needs the GIL
Fixes #174
=> fix: Cython compile error with Cython 3

jack_mixer/channel.py
=> fix: sync output channel name change to input channel control groups

INSTALL.md, data/meson.build, docs/meson.build, jack_mixer/meson.build, meson.build, pyproject.toml
... for PEP-517 compatible builds
=> feat: replace 'mesonpep517' with 'meson-python' 

docs/jack_mixer.1.rst.in, src/_jack_mixer.pyx
Minor spelling errors in some of the source code
=> fix: correct spelling errors in comments
